<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="packages" nsURI="http://packages/1.0" nsPrefix="packages">
  <eSubpackages name="Parametres">
    <eClassifiers xsi:type="ecore:EClass" name="Parametres" eSuperTypes="#//Parametres/InterParam">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="langue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterParam" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="Vue">
    <eClassifiers xsi:type="ecore:EClass" name="Carte">
      <eOperations name="dezoomer" lowerBound="1"/>
      <eOperations name="zoomer" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="barbules" upperBound="-1"
          eType="#//Vue/Barbule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="zoneSelection" eType="#//Vue/ZoneSelection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="zonePression" upperBound="-1"
          eType="#//Vue/ZonePression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Barbule">
      <eOperations name="createBarb" lowerBound="1">
        <eParameters name="temps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="pression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="vitesse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="afficherBarb" lowerBound="1">
        <eParameters name="donnee" eType="#//Prevision/Vent"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterView" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fenetre" eSuperTypes="#//Vue/InterView">
      <eStructuralFeatures xsi:type="ecore:EReference" name="carte" lowerBound="1"
          eType="#//Vue/Carte"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ZonePression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ZoneSelection"/>
  </eSubpackages>
  <eSubpackages name="Edition">
    <eClassifiers xsi:type="ecore:EClass" name="Edit Donnee" eSuperTypes="#//Edition/Edtion">
      <eOperations name="changeDirection" lowerBound="1">
        <eParameters name="donnee" eType="#//Prevision/Donnee"/>
        <eParameters name="dir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="changePression" lowerBound="1">
        <eParameters name="donnee" eType="#//Prevision/Donnee"/>
        <eParameters name="pression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="changeContraste" lowerBound="1">
        <eParameters name="donnee" eType="#//Prevision/Donnee"/>
        <eParameters name="contraste" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateDonnee" eSuperTypes="#//Edition/Edtion">
      <eOperations name="create" lowerBound="1" eType="#//Prevision/Donnee">
        <eParameters name="temps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="pression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="vitesse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterEdit" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Edtion" eSuperTypes="#//Edition/InterEdit"/>
  </eSubpackages>
  <eSubpackages name="Calcul" nsURI="" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Calcul" eSuperTypes="#//Calcul/InterCalc">
      <eOperations name="interpoler" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="prev1" eType="#//Prevision/Donnee"/>
        <eParameters name="prev2" eType="#//Prevision/Donnee"/>
        <eParameters name="prev3" eType="#//Prevision/Donnee"/>
        <eParameters name="prev4" eType="#//Prevision/Donnee"/>
        <eParameters name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="moyDonnee" lowerBound="1" eType="#//Prevision/Donnee">
        <eParameters name="listDonnee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterCalc" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="Prevision">
    <eClassifiers xsi:type="ecore:EClass" name="Donnee">
      <eStructuralFeatures xsi:type="ecore:EReference" name="coord" lowerBound="1"
          eType="#//Prevision/Coordonnee"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temps" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Vent" eSuperTypes="#//Prevision/Donnee">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vitesse_u" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vitesse_v" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pressions" eSuperTypes="#//Prevision/Donnee">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Coordonnee">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lon" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterPrev" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Prevision" eSuperTypes="#//Prevision/InterPrev">
      <eStructuralFeatures xsi:type="ecore:EReference" name="donnees" lowerBound="1"
          upperBound="-1" eType="#//Prevision/Donnee"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="IO">
    <eClassifiers xsi:type="ecore:EClass" name="FileReader" eSuperTypes="#//IO/InterRead">
      <eOperations name="parseFile" lowerBound="1">
        <eParameters name="path_to_file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getDonnees" lowerBound="1" eType="#//Prevision/Donnee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetcdfWriter" eSuperTypes="#//IO/InterWrite"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterRead" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterWrite" abstract="true" interface="true"/>
  </eSubpackages>
</ecore:EPackage>
